# Generated by Django 4.0.4 on 2022-06-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_delete_my'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(verbose_name='Тема')),
                ('name', models.CharField(max_length=100, verbose_name='Келген коноктун аты')),
                ('data', models.CharField(max_length=30, verbose_name='Күнү, айы, сааты')),
                ('address', models.TextField(verbose_name='Адреси')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Аты')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Фамилиясы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Аты'),
        ),
    ]
