# Generated by Django 4.0.4 on 2022-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_advertising_comment_delete_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='аты')),
                ('header', models.TextField(verbose_name='Заголовок')),
            ],
        ),
    ]
