# Generated by Django 4.0.4 on 2022-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowers',
            name='price',
            field=models.FloatField(default=1, verbose_name='баасы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowers',
            name='title',
            field=models.CharField(max_length=100, verbose_name='аты'),
        ),
    ]
